# Generated by Django 5.0.4 on 2024-10-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'secciones',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.grado')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.seccion')),
            ],
            options={
                'db_table': 'aulas',
            },
        ),
    ]
