# Generated by Django 5.1.1 on 2024-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('firsname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('numberphome', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
